import fs from 'node:fs'
import prettier from 'prettier'

const ARTIFACTS_DIR = './artifacts'
const TARGET_DIR = '../core-abi/src'

const generatedContractComment = `
/**
 * This file is autogenerated.
 * You should not edit it manually or your changes might be overwritten.
 */
`

function getDirectories(path: string) {
  return fs
    .readdirSync(path, { withFileTypes: true })
    .filter((dirent) => dirent.isDirectory())
    .map((dirent) => dirent.name)
}

function getContractDataFromArtifacts() {
  const contractsDir = `${ARTIFACTS_DIR}/contracts`
  if (!fs.existsSync(contractsDir)) {
    throw Error('Compilation for some contracts should be done at first.')
  }
  const output = {} as Record<string, any>
  for (const contractFullName of getDirectories(contractsDir)) {
    const contractName = contractFullName.split('.')[0]
    if (contractName) {
      const { abi } = JSON.parse(
        fs
          .readFileSync(
            `${contractsDir}/${contractFullName}/${contractName}.json`
          )
          .toString()
      )
      output[contractName] = {
        abi,
      }
    }
  }
  return output
}

async function main() {
  if (!fs.existsSync(TARGET_DIR)) {
    fs.mkdirSync(TARGET_DIR)
  }
  const fileContent = JSON.stringify(getContractDataFromArtifacts())
  fs.writeFileSync(
    `${TARGET_DIR}/index.ts`,
    prettier.format(
      `${generatedContractComment} const deployedContracts = ${fileContent} as const; \n\n export default deployedContracts`,
      {
        parser: 'typescript',
      }
    )
  )
}

main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
