/**
 * This file is autogenerated.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from '@/lib/contract'

const deployedContracts = {} as const

export default deployedContracts satisfies GenericContractsDeclaration
